### ISSUE TITLE
Prover (Validate msgs from Axelar)

### ISSUE THREAD

**Issue by roberts-ivanovs** [eigerco/axelar-amplifier#1]
- [ ] **Axelar Smart Contract:** Contract that communicates with the off chain component and aggregate signatures that outgoing msg is fine + Multisig contract
- [ ] **off-chain component:** Off-chain workers with stake that verify if msg was processed on Axelar. FORK [`ampd`](https://github.com/axelarnetwork/axelar-amplifier/tree/main/ampd) FOR THIS

**Comment by ctoyan** [comment]
Since [we're planning](https://eig3r.slack.com/archives/C06A2QAPE2Z/p1708691051203939?thread_ts=1708690286.097019&cid=C06A2QAPE2Z) to use the default prover and verifier - this ticket will most probably not be needed.

Closing it and if for some reason we need prover changes, we'll open a specific ticket.
